# render.yaml – cấu hình deploy cho Render
services:
  - type: web
    name: scrape-api
    env: python
    buildCommand: ""
    startCommand: uvicorn main:app --host=0.0.0.0 --port=10000
    autoDeploy: true
